name: CI
on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: ls
        run: ls -alh $GITHUB_WORKSPACE

      - name: update apt
        run: sudo apt-get update

      - name: install basic tools
        run: sudo apt-get install -y git curl docker.io containerd runc

      - name: Creates a Docker image of the template node
        run: docker build . -t t3rn-faucet:1.0

      - name: List images
        run: docker image ls

      - name: List images
        run: docker image ls

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishes the image to GHCR
        run: |
          DOCKER_IMAGE_ID=$( docker image ls | grep t3rnsubstrate | awk '{ print $3 }' )
          docker tag $DOCKER_IMAGE_ID ghcr.io/phpengine/faucet:latest
          docker push ghcr.io/phpengine/faucet:latest


